learning_log/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    #主题页
    path(r'',include('learning_logs.urls',namespace='learning_logs')),
    #用户登陆注册
    path(r'^users/',include('users.urls',namespace='users'))

]

learning_logs/urls.py
"""定义learning_logs的URL模式"""
from django.urls import path
from . import views
urlpatterns = [
    #主页
    path(r'',views.index,name='index'),
    path(r'topics/$',views.topics,name='topics'),
    #特定主题页的详细页面
    path(r'^topics/(?P<topic_id>\d+)/$',views.topic,name='topic'),
    #新建主题的url模式
    path(r'^new_topic/$',views.new_topic,name='new_topic'),
    #新的主体条目
    path(r'^new_entry/(?P<topic_id>\d+)/$',views.new_entry,name='new_entry'),
    #编辑条目
    path(r'^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry,name='edit_entry')
]
app_name = 'learning_logs'

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from . import views
urlpatterns =[
    #登陆页面
    path(r'^login/$',LoginView.as_view(template_name='users/login.html'),name='login'),
    path(r'^logout/$',views.logout_view,name = 'logout'),
    path(r'^register/$',views.register,name='register')
]
app_name = 'users'

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
"""属性text是一个CharField——由字符或文本组成的数据
（见❶）。需要存储少量的文本，如名称、标题或城市时，
可使用CharField。定义CharField属性时，
必须告诉Django该在数据库中预留多少空间。在这里，
我们将max_length设置成了200（即200个字符），
这对存储大多数主题名来说足够了。
属性date_added是一个DateTimeField——记录日期
和时间的数据（见❷）。我们传递了实参auto_now_add=True，
每当用户创建新主题时，这都让Django将这个属性自动设置成
当前日期和时间。"""
class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    owner = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


"""像Topic一样，Entry也继承了Django基类Model（见❶）
。第一个属性topic是一个ForeignKey实例（见❷）。
外键是一个数据库术语，它引用了数据库中的另一条记录；
这些代码将每个条目关联到特定的主题。每个主题创建时，
都给它分配了一个键（或ID）。需要在两项数据之间建立联系时，
Django使用与每项信息相关联的键。稍后我们将根据这些联系获
取与特定主题相关联的所有条目。接下来是属性text，它是一个
TextField实例（见❸）。这种字段不需要长度限制，因为我们不
想限制条目的长度。属性date_added让我们能够按创建顺序呈现条目
，并在每个条目旁边放置时间戳。在❹处，我们在Entry类中嵌套了
Meta类。Meta存储用于管理模型的额外信息，在这里，它让我们能
够设置一个特殊属性，让Django在需要时使用Entries来表示多个
条目。如果没有这个类， Django将使用Entrys来表示多个条目。
最后，方法__str__()告诉Django，呈现条目时应显示哪些信息。
由于条目包含的文本可能很长，（见❺）。我们还添加了一个省略"""
class Entry(models.Model):
    """学到的有关某个主题的具体知识
    老版本钟on_delete=models.CASCADE是默认设置
    """
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
        """返回模型的字符串表示"""
        if len(self.text) >= 50:
            return self.text[:50]+'...'
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from  .models import Topic,Entry
class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from .forms import TopicForm,EntryForm
from .models import Topic, Entry
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    """学习笔记的主页"""
    return render(request,'learning_logs/index.html')

@login_required
def topics(request):
    """显示所有的主题"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    content = {'topics':topics}
    return render(request,'learning_logs/topics.html',content)

@login_required
def topic(request,topic_id):
    """显示单个主题及其所有的条目"""
    topic = Topic.objects.get(id=topic_id)
    #确认请求的主体属于当前用户
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    content = {'topic':topic,'entries':entries}
    return render(request,'learning_logs/topic.html',content)

@login_required
def new_topic(request):
    #用户过滤器

    """添加新主题"""
    if request.method != 'POST':
        #未提交数据，创建一个新表单
        form = TopicForm()
    else:
        #POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form':form}
    return render(request,'learning_logs/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
    """特定的主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        #提交新数据，创建新表单
        form = EntryForm()
    else:
        form = EntryForm(data = request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))
    context = {'topic':topic,'form':form}
    return render(request,'learning_logs/new_entry.html',context)

@login_required
def edit_entry(request,entry_id):
    entry = Entry.objects.get(id = entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        #初次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        #POST提交的数据，对数据进行处理
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))
    context = {'entry':entry,'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    """注册新用户"""
    if request.method != 'POST':
        #显示空的注册表单
        form = UserCreationForm()
    else:
        #处理填写好的表单
        form = UserCreationForm(data = request.POST)
        if form.is_valid():
            new_user = form.save()
            #让用户自动登陆，再重定向到主页
            authenticated_user = authenticate(username=new_user.username,password=request.POST['password1'])
            login(request,authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form':form}
    return render(request,'users/register.html',context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>学习笔记</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <!--Static navbar-->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#navbar" aria-expanded="false" aria-controls="navbar"></button>
                <a class="navbar-brand" href="{% url 'learning_logs:index' %}">学习日记</a>
            </div>
            <div id="navbar" class="navbar-collapse collapsed">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_logs:topics' %}">学习主题</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li><a>你好，{{ user.username }}</a></li>
                        <li><a href="{% url 'users:logout' %}">注销</a></li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}">注册</a></li>
                        <li><a href="{% url 'users:login' %}">登陆</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}
{% block header %}
    <h2>修改笔记</h2>
{% endblock header %}
{% block content %}
<form method="post" action="{% url 'learning_logs:edit_entry' entry.id %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">保存</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
</form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
<!--extends继承父模版-->
{% extends 'learning_logs/base.html' %}
{% block header %}
    <div class="jumbotron">
        <h1>学习轨迹</h1>
    </div>
{% endblock header %}
{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">注册一个账户,记录你的学习主题和心得</a>
    </h2>
    <h2>
        学习新主题，记录心得
    </h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>条目添加</title>
</head>
<body>
    <P>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </P>
    <P>添加新条目:</P>
    <form action="{% url 'learning_logs:new_entry' topic.id%}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="subit">添加条目</button>
    </form>
</body>
</html>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}
{% block header %}
    <h2>添加新的学习主题</h2>
{% endblock header %}
{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">添加新主题</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}
{% block content %}
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">添加新笔记</a>
    </p>
    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added|date:'Y M d,H:i' }}
                    <small>
                        <a href="{% url 'learning_logs:edit_entry' entry.id %}">修改笔记</a>
                    </small>
                </h3>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
        {% empty %}
        此主题没有笔记
    {% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}
{% block header %}
    <h1>主题</h1>
{% endblock header %}
{% block content %}
    <ul>
    {% for topic in topics %}
        <li>
            <h3>
                <a href="{% url 'learning_logs:topic' topic.id%}">{{ topic }}</a>
            </h3>
        </li>
    {% empty %}
        <li>没有新的学习主题</li>
    {% endfor %}
    </ul>
    <h3>
        <a href="{% url 'learning_logs:new_topic' %}">添加新主题</a>
    </h3>
{% endblock content %}

users/templates/users/login.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}
{% block header %}
    <h2>记录你的笔记</h2>
{% endblock header %}
{% block content %}
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">登陆</button>
        {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}
{% block header %}
    <h2>注册账户</h2>
{% endblock header %}
{% block content %}
    <form method="post" action="{% url 'users:register' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button name="submit" class="btn btn-primary">注册</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>
{% endblock content %}